qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='50' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='100' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='200' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='300' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='400' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='500' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='600' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='700' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='800' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='900' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='logic',linewidthKHz='200',loopBandWidthMHz='1000' qpsk_analog_delay_penalty_qsub.sh

qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='50' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='100' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='200' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='300' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='400' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='500' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='600' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='700' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='800' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='900' qpsk_analog_delay_penalty_qsub.sh
qsub -v CPR='OPLL',CPRmethod='costas',linewidthKHz='200',loopBandWidthMHz='1000' qpsk_analog_delay_penalty_qsub.sh