qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="2.0" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.9" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.8" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.7" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.6" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.5" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.4" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.3" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.2" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.1" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Logic",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.0" epll_ssb_mixer_distortion_qsub.sh

qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="2.0" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.9" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.8" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.7" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.6" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.5" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.4" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.3" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.2" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.1" epll_ssb_mixer_distortion_qsub.sh
qsub -v fiberLengthKm="0",ModBWGHz="25",CPRmethod="Costas",CPRNpol="1",linewidthKHz="200",Delayps="200",mixerVamp="1.0" epll_ssb_mixer_distortion_qsub.sh