qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='0',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='1',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='2',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='3',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='4',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='5',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='6',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='7',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='8',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='9',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='10',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='11',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='12',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='13',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='14',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='1',fiberLengthKm='15',ModBWGHz='30' ofdm_ber_qsub.sh


qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='0',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='1',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='2',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='3',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='4',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='5',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='6',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='7',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='8',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='9',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='10',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='11',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='12',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='13',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='14',ModBWGHz='30' ofdm_ber_qsub.sh
qsub -v OFDMtype='DC-OFDM',Amplified='0',fiberLengthKm='15',ModBWGHz='30' ofdm_ber_qsub.sh