#!/bin/bash

########## 
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="10",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="15",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="20",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="25",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="30",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="35",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="40",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="45",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="50",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="55",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="60",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="65",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="70",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="75",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="80",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="85",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="90",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="95",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="1480",pumpPowermW="100",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh

qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="10",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="15",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="20",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="25",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="30",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="35",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="40",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="45",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="50",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="55",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="60",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="65",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="70",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="75",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="80",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="85",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="90",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="95",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type3",pumpWavelengthnm="980",pumpPowermW="100",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh

qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="10",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="15",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="20",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="25",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="30",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="35",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="40",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="45",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="50",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="55",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="60",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="65",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="70",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="75",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="80",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="85",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="90",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="95",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="1480",pumpPowermW="100",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh

qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="10",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="15",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="20",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="25",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="30",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="35",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="40",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="45",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="50",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="55",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="60",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="65",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="70",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="75",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="80",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="85",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="90",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="95",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
qsub -v edf_type="principles_type2",pumpWavelengthnm="980",pumpPowermW="100",Nspans="280",spanLengthKm="50" capacity_vs_pump_power_qsub.sh
